apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # ...
spec:
  selector:
    matchLabels:
      namespace: <login>
  # ...

# Each PersistentVolume is already configured inside the home of each student at /home/<login>/project2-pv2 folder, using the Kubernetes's name of project2-pv2-<login> and one distinct storageClassName per student given by default-storage-class-<login>.